env:
  global:
  - TERM=dumb
    # This will supress any download for dependencies and plugins or upload messages which would clutter the console log.
    # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  - MAVEN_OPTS="-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
    # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
    # when running from the command line.
    # `installAtEnd` and `deployAtEnd`are only effective with recent version of the corresponding plugins.
  - MAVEN_CLI_OPT="--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
language: java
jdk:
  - oraclejdk8

branches:
  only:
    - master
install: /bin/true
script: "mvn clean install"
#script: "mvn clean install -DcreateChecksum=true"
#script:
#  ./run-rdfunit.sh
notifications:
  email:
    recipients:
      - gpublio@gmail.com
      - hellmann@informatik.uni-leipzig.de
    on_success: change
    on_failure: change
