env:
  global:
  - TERM=dumb
language: java
jdk:
  - oraclejdk8

branches:
  only:
    - master

before_script:
  - mvn clean test-compile
script:
  - mvn install verify
  # - "mvn clean install -DcreateChecksum=true"
  # - ./run-rdfunit.sh
notifications:
  email:
    recipients:
      - gpublio@gmail.com
      - hellmann@informatik.uni-leipzig.de
    on_success: change
    on_failure: change
